version: 2

project_name: tpd

builds:
  - main: ./cmd/tpd
    binary: tpd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  use: git

release:
  github:
    owner: jgillich
    name: tpd
