#!/usr/bin/env python3
"""Generate the light README banner from the canonical dark SVG."""

from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets" / "tpd-banner.svg"
LIGHT = ROOT / "assets" / "tpd-banner-light.svg"

COLORS = {
    "#0b0d14": "#f8fafc",
    "#111420": "#f1f5f9",
    "#0d101a": "#e2e8f0",
    "#171b28": "#ffffff",
    "#141824": "#f8fafc",
    "#0f121b": "#f1f5f9",
    "#f5f0e6": "#334155",
    "#272d3f": "#cbd5e1",
    "#232838": "#cbd5e1",
    "#181d2b": "#e2e8f0",
    "#252b3d": "#cbd5e1",
    "#1b202e": "#f1f5f9",
    "#2c344a": "#cbd5e1",
    "#232a3d": "#cbd5e1",
    "#2a3144": "#cbd5e1",
    "#cbd5e1": "#334155",
    "#ffffff": "#0f172a",
    "#94a3b8": "#475569",
}


def replace_color(match: re.Match[str]) -> str:
    color = match.group(0).lower()
    return COLORS.get(color, color)


def main() -> None:
    source = SOURCE.read_text()
    light = re.sub(r"#[0-9a-fA-F]{6}", replace_color, source)
    declaration, separator, body = light.partition("\n")
    marker = "<!-- Generated by scripts/generate-banner.py; edit assets/tpd-banner.svg instead. -->\n"
    if declaration.startswith("<?xml"):
        LIGHT.write_text(declaration + "\n" + marker + body)
    else:
        LIGHT.write_text(marker + light)


if __name__ == "__main__":
    main()
