package scaffold

import (
	"bufio"
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/jgillich/toolpod/internal/profile"
	"golang.org/x/term"
	"gopkg.in/yaml.v3"
)

type Options struct {
	Profile     string
	Presets     []string
	Force       bool
	DryRun      bool
	Interactive bool
	ProfileDir  string
}

const headerMarker = "# Generated by toolpod init."

func Run(ctx context.Context, opts Options, stdin io.Reader, stdout, stderr io.Writer) error {
	// Determine profile dir
	userDir := opts.ProfileDir
	if userDir == "" {
		userDir = profile.DefaultProfileDir()
	}
	if userDir == "" {
		return fmt.Errorf("cannot determine profile directory (set XDG_CONFIG_HOME)")
	}

	// Determine if interactive. The CLI sets opts.Interactive via IsTTY;
	// tests set it directly so the wizard is exercisable with strings.NewReader.
	interactive := opts.Interactive

	// Shared buffered reader for interactive prompts. Creating separate
	// bufio.NewReader values per prompt would lose buffered data from the
	// same underlying stdin.
	reader := bufio.NewReader(stdin)

	// Validate profile is a built-in (load once, reuse for prompt)
	builtinCat, err := profile.LoadProfiles("")
	if err != nil {
		return fmt.Errorf("loading built-in profiles: %w", err)
	}
	if len(builtinCat.Names()) == 0 {
		return fmt.Errorf("no built-in profiles available")
	}

	// Resolve profile name (prompt if interactive and not provided)
	profileName := opts.Profile
	if profileName == "" {
		if !interactive {
			return fmt.Errorf("profile name is required")
		}
		profileName = promptProfile(builtinCat.Names(), reader, stderr)
		if profileName == "" {
			return fmt.Errorf("profile name is required")
		}
	}

	if _, ok := builtinCat.Get(profileName); !ok {
		return fmt.Errorf("unknown built-in profile: %s\navailable built-in profiles: %s", profileName, strings.Join(builtinCat.Names(), ", "))
	}

	// Resolve presets (prompt if interactive and not provided via flag)
	presetNamesList := PresetNames()
	selectedPresets := opts.Presets
	if len(selectedPresets) == 0 && interactive {
		selectedPresets = promptPresets(presetNamesList, reader, stderr)
	}

	// Validate preset names
	for _, p := range selectedPresets {
		if _, ok := presets[p]; !ok {
			hint := ""
			if p == "all" {
				hint = "\nnote: there is no \"all\" shorthand; specify presets explicitly"
			}
			return fmt.Errorf("unknown preset: %s\navailable presets: %s%s", p, strings.Join(presetNamesList, ", "), hint)
		}
	}

	// Dedup presets
	selectedPresets = dedup(selectedPresets)

	// Check host-side existence of file preset sources (spec §10b)
	checkPresetFiles(selectedPresets, stderr)

	// Generate the profile content
	content, err := generate(profileName, selectedPresets)
	if err != nil {
		return fmt.Errorf("generating profile: %w", err)
	}

	// Determine target path
	targetPath := filepath.Join(userDir, profileName+".yaml")

	// Dry run
	if opts.DryRun {
		fmt.Fprintf(stdout, "# dry-run: would write %s\n", targetPath)
		fmt.Fprint(stdout, content)
		// Validate via temp dir
		if err := validateViaTempDir(content, profileName); err != nil {
			return fmt.Errorf("generated config failed validation: %w", err)
		}
		return nil
	}

	// Check existing file
	if _, err := os.Stat(targetPath); err == nil {
		if !opts.Force {
			return fmt.Errorf("%s already exists (use --force to overwrite)", targetPath)
		}
		// Force: check marker in interactive mode
		if interactive {
			existing, err := os.ReadFile(targetPath)
			if err == nil && !strings.HasPrefix(string(existing), headerMarker) {
				fmt.Fprintf(stderr, "%s exists and was not generated by toolpod.\nOverwrite? [y/N]: ", targetPath)
				line, _ := reader.ReadString('\n')
				line = strings.TrimSpace(strings.ToLower(line))
				if line != "y" && line != "yes" {
					fmt.Fprintf(stdout, "skipped %s\n", targetPath)
					return nil
				}
			}
		}
	}

	// Create directory
	if err := os.MkdirAll(userDir, 0o700); err != nil {
		return fmt.Errorf("creating profile directory: %w", err)
	}

	// Write file
	if err := os.WriteFile(targetPath, []byte(content), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", targetPath, err)
	}

	// Validate after writing via isolated temp dir to avoid collateral
	// deletion from pre-existing broken sibling YAML files in userDir.
	if err := validateViaTempDir(content, profileName); err != nil {
		os.Remove(targetPath)
		return fmt.Errorf("generated config failed validation: %w", err)
	}

	fmt.Fprintf(stdout, "created %s\n", targetPath)
	fmt.Fprintln(stdout, "generated config is valid")
	return nil
}

func generate(profileName string, selectedPresets []string) (string, error) {
	base := profile.RawProfile{Profile: profile.Profile{
		Version: 1,
	}}
	for _, name := range selectedPresets {
		base = profile.MergeProfiles(base, presets[name])
	}
	base.Extends = profileName // set after merge; MergeProfiles clears Extends

	data, err := yaml.Marshal(base.Profile)
	if err != nil {
		return "", err
	}

	header := headerMarker + "\n" +
		fmt.Sprintf("# This user profile overrides the built-in %q profile.\n", profileName) +
		"# Remove this file to restore the built-in default.\n\n"

	return header + string(data), nil
}

func validateViaTempDir(content, profileName string) error {
	tmpDir, err := os.MkdirTemp("", "toolpod-init-validate-*")
	if err != nil {
		return err
	}
	defer os.RemoveAll(tmpDir)

	// Write the full content (YAML comments are valid YAML, no stripping needed)
	if err := os.WriteFile(filepath.Join(tmpDir, profileName+".yaml"), []byte(content), 0o644); err != nil {
		return err
	}

	cat, err := profile.LoadProfiles(tmpDir)
	if err != nil {
		return err
	}
	_, err = profile.ResolveProfile(cat, profileName)
	return err
}

func dedup(items []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, item := range items {
		item = strings.TrimSpace(item)
		if item == "" || seen[item] {
			continue
		}
		seen[item] = true
		out = append(out, item)
	}
	return out
}

// IsTTY reports whether r is an interactive terminal.
// The CLI calls this to set Options.Interactive before calling Run;
// tests set Options.Interactive directly so they can use strings.NewReader.
func IsTTY(r io.Reader) bool {
	if f, ok := r.(*os.File); ok {
		return term.IsTerminal(int(f.Fd()))
	}
	return false
}

func promptProfile(names []string, reader *bufio.Reader, stderr io.Writer) string {
	fmt.Fprintf(stderr, "Available built-in profiles: %s\n", strings.Join(names, ", "))
	fmt.Fprintf(stderr, "Profile: ")
	line, _ := reader.ReadString('\n')
	return strings.TrimSpace(line)
}

func promptPresets(names []string, reader *bufio.Reader, stderr io.Writer) []string {
	fmt.Fprintf(stderr, "Presets (%s) [none]: ", strings.Join(names, ", "))
	line, _ := reader.ReadString('\n')
	line = strings.TrimSpace(line)
	if line == "" {
		return nil
	}
	return strings.Split(line, ",")
}

// checkPresetFiles warns to stderr when a file preset's source path does
// not exist on the host (spec §10b). Only leading "~" is expanded; absolute
// paths and paths without "~" are skipped (no host-side check needed).
func checkPresetFiles(selectedPresets []string, stderr io.Writer) {
	home, err := os.UserHomeDir()
	if err != nil {
		return
	}
	for _, name := range selectedPresets {
		p, ok := presets[name]
		if !ok {
			continue
		}
		for target, mount := range p.Mounts {
			// Only expand a leading "~/" or exact "~" — don't touch
			// absolute paths or paths with "~" in the middle.
			var src string
			if strings.HasPrefix(mount.Source, "~/") {
				src = home + mount.Source[1:]
			} else if mount.Source == "~" {
				src = home
			} else {
				continue
			}
			if _, err := os.Stat(src); err != nil {
				fmt.Fprintf(stderr, "warning: %s does not exist; the mount %s will create an empty directory.\n         Create the file first or remove this preset.\n", mount.Source, target)
			}
		}
	}
}
