package scaffold

import (
	"bufio"
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/charmbracelet/huh"
	"github.com/jgillich/toolpod/internal/profile"
	"golang.org/x/term"
	"gopkg.in/yaml.v3"
)

type Options struct {
	Profile     string
	Fragments   []string
	Force       bool
	DryRun      bool
	Interactive bool
	ProfileDir  string
}

const headerMarker = "# Generated by toolpod init."

func Run(ctx context.Context, opts Options, stdin io.Reader, stdout, stderr io.Writer) error {
	// Determine profile dir
	userDir := opts.ProfileDir
	if userDir == "" {
		userDir = profile.DefaultProfileDir()
	}
	if userDir == "" {
		return fmt.Errorf("cannot determine profile directory (set XDG_CONFIG_HOME)")
	}

	// Determine if interactive. The CLI sets opts.Interactive via IsTTY;
	// tests set it directly so the wizard is exercisable with strings.NewReader.
	interactive := opts.Interactive

	// tty reports whether stdin is an actual terminal. When true, we use
	// charmbracelet/huh for interactive TUI prompts; otherwise we fall back
	// to simple text prompts so tests with strings.NewReader still work.
	tty := IsTTY(stdin)

	// wizardUsed tracks whether interactive prompts for profile/fragments were
	// actually shown. When the user provides all args explicitly (even in a
	// TTY), we skip the overwrite prompt to avoid surprising prompts.
	wizardUsed := false

	// Shared buffered reader for interactive prompts. Creating separate
	// bufio.NewReader values per prompt would lose buffered data from the
	// same underlying stdin.
	reader := bufio.NewReader(stdin)

	// Validate profile is a built-in (load once, reuse for prompt)
	builtinCat, err := profile.LoadProfiles("")
	if err != nil {
		return fmt.Errorf("loading built-in profiles: %w", err)
	}
	if len(builtinCat.Names()) == 0 {
		return fmt.Errorf("no built-in profiles available")
	}

	// Resolve profile name (prompt if interactive and not provided)
	profileName := opts.Profile
	if profileName == "" {
		if !interactive {
			return fmt.Errorf("profile name is required")
		}
		if tty {
			profileName, err = promptProfileHuh(builtinCat.Names(), stdin, stdout)
			if err != nil {
				return err
			}
		} else {
			profileName = promptProfile(builtinCat.Names(), reader, stderr)
		}
		wizardUsed = true
		if profileName == "" {
			return fmt.Errorf("profile name is required")
		}
	}

	if _, ok := builtinCat.Get(profileName); !ok {
		return fmt.Errorf("unknown built-in profile: %s\navailable built-in profiles: %s", profileName, strings.Join(builtinCat.Names(), ", "))
	}

	// Resolve fragments (prompt if interactive and not provided via flag)
	fragmentNamesList := FragmentNames()
	selectedFragments := opts.Fragments
	if len(selectedFragments) == 0 && interactive {
		if tty {
			selectedFragments, err = promptFragmentsHuh(fragmentNamesList, stdin, stdout)
			if err != nil {
				return err
			}
		} else {
			selectedFragments = promptFragments(fragmentNamesList, reader, stderr)
		}
		wizardUsed = true
	}

	// Validate fragment names
	for _, p := range selectedFragments {
		if _, ok := Fragments()[p]; !ok {
			hint := ""
			if p == "all" {
				hint = "\nnote: there is no \"all\" shorthand; specify fragments explicitly"
			}
			return fmt.Errorf("unknown fragment: %s\navailable fragments: %s%s", p, strings.Join(fragmentNamesList, ", "), hint)
		}
	}

	// Dedup fragments
	selectedFragments = dedup(selectedFragments)

	// Check host-side existence of file fragment sources (spec §10b)
	checkFragmentFiles(selectedFragments, stderr)

	// Generate the profile content
	content, err := generate(profileName, selectedFragments)
	if err != nil {
		return fmt.Errorf("generating profile: %w", err)
	}

	// Determine target path
	targetPath := filepath.Join(userDir, profileName+".yaml")

	// Dry run
	if opts.DryRun {
		fmt.Fprintf(stdout, "# dry-run: would write %s\n", targetPath)
		fmt.Fprint(stdout, content)
		// Validate via temp dir
		if err := validateViaTempDir(content, profileName); err != nil {
			return fmt.Errorf("generated config failed validation: %w", err)
		}
		return nil
	}

	// Check existing file
	if _, err := os.Stat(targetPath); err == nil {
		existing, _ := os.ReadFile(targetPath)
		managed := len(existing) > 0 && strings.HasPrefix(string(existing), headerMarker)

		needPrompt := false
		if !opts.Force {
			if !wizardUsed {
				return fmt.Errorf("%s already exists (use --force to overwrite)", targetPath)
			}
			// Interactive wizard was used: confirm overwrite
			needPrompt = true
		} else if interactive && !managed {
			// --force + interactive + non-managed file: still confirm
			needPrompt = true
		}

		if needPrompt {
			if tty {
				confirmed, err := promptOverwriteHuh(targetPath, managed, stdin, stdout)
				if err != nil {
					return err
				}
				if !confirmed {
					fmt.Fprintf(stdout, "skipped %s\n", targetPath)
					return nil
				}
			} else {
				if !managed {
					fmt.Fprintf(stderr, "%s exists and was not generated by toolpod.\n", targetPath)
				} else {
					fmt.Fprintf(stderr, "%s already exists. ", targetPath)
				}
				fmt.Fprintf(stderr, "Overwrite? [y/N]: ")
				line, _ := reader.ReadString('\n')
				line = strings.TrimSpace(strings.ToLower(line))
				if line != "y" && line != "yes" {
					fmt.Fprintf(stdout, "skipped %s\n", targetPath)
					return nil
				}
			}
		}
	}

	// Create directory
	if err := os.MkdirAll(userDir, 0o700); err != nil {
		return fmt.Errorf("creating profile directory: %w", err)
	}

	// Write file
	if err := os.WriteFile(targetPath, []byte(content), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", targetPath, err)
	}

	// Validate after writing via isolated temp dir to avoid collateral
	// deletion from pre-existing broken sibling YAML files in userDir.
	if err := validateViaTempDir(content, profileName); err != nil {
		os.Remove(targetPath)
		return fmt.Errorf("generated config failed validation: %w", err)
	}

	fmt.Fprintf(stdout, "created %s\n", targetPath)
	fmt.Fprintln(stdout, "generated config is valid")
	return nil
}

func generate(profileName string, selectedFragments []string) (string, error) {
	base := profile.RawProfile{Profile: profile.Profile{
		Version: 1,
	}}
	for _, name := range selectedFragments {
		base = profile.MergeProfiles(base, Fragments()[name])
	}
	base.ExtendsList = profile.ExtendsList{profileName} // set after merge; MergeProfiles clears ExtendsList

	data, err := yaml.Marshal(base.Profile)
	if err != nil {
		return "", err
	}

	header := headerMarker + "\n" +
		fmt.Sprintf("# This user profile overrides the built-in %q profile.\n", profileName) +
		"# Remove this file to restore the built-in default.\n\n"

	return header + string(data), nil
}

func validateViaTempDir(content, profileName string) error {
	tmpDir, err := os.MkdirTemp("", "toolpod-init-validate-*")
	if err != nil {
		return err
	}
	defer os.RemoveAll(tmpDir)

	// Write the full content (YAML comments are valid YAML, no stripping needed)
	if err := os.WriteFile(filepath.Join(tmpDir, profileName+".yaml"), []byte(content), 0o644); err != nil {
		return err
	}

	cat, err := profile.LoadProfiles(tmpDir)
	if err != nil {
		return err
	}
	_, err = profile.ResolveProfile(cat, profileName)
	return err
}

func dedup(items []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, item := range items {
		item = strings.TrimSpace(item)
		if item == "" || seen[item] {
			continue
		}
		seen[item] = true
		out = append(out, item)
	}
	return out
}

// IsTTY reports whether r is an interactive terminal.
// The CLI calls this to set Options.Interactive before calling Run;
// tests set Options.Interactive directly so they can use strings.NewReader.
func IsTTY(r io.Reader) bool {
	if f, ok := r.(*os.File); ok {
		return term.IsTerminal(int(f.Fd()))
	}
	return false
}

func promptProfile(names []string, reader *bufio.Reader, stderr io.Writer) string {
	fmt.Fprintf(stderr, "Available built-in profiles: %s\n", strings.Join(names, ", "))
	fmt.Fprintf(stderr, "Profile: ")
	line, _ := reader.ReadString('\n')
	return strings.TrimSpace(line)
}

func promptFragments(names []string, reader *bufio.Reader, stderr io.Writer) []string {
	fmt.Fprintf(stderr, "Fragments (%s) [none]: ", strings.Join(names, ", "))
	line, _ := reader.ReadString('\n')
	line = strings.TrimSpace(line)
	if line == "" {
		return nil
	}
	return strings.Split(line, ",")
}

func promptProfileHuh(names []string, stdin io.Reader, stdout io.Writer) (string, error) {
	var selected string
	opts := make([]huh.Option[string], len(names))
	for i, n := range names {
		opts[i] = huh.NewOption(n, n)
	}
	form := huh.NewForm(
		huh.NewGroup(
			huh.NewSelect[string]().
				Title("Select a built-in profile").
				Options(opts...).
				Value(&selected),
		),
	).WithInput(stdin).WithOutput(stdout)
	if err := form.Run(); err != nil {
		return "", err
	}
	return selected, nil
}

func promptFragmentsHuh(names []string, stdin io.Reader, stdout io.Writer) ([]string, error) {
	var selected []string
	opts := make([]huh.Option[string], len(names))
	for i, n := range names {
		opts[i] = huh.NewOption(n, n)
	}
	form := huh.NewForm(
		huh.NewGroup(
			huh.NewMultiSelect[string]().
				Title("Select fragments (space to toggle, enter to confirm)").
				Options(opts...).
				Value(&selected),
		),
	).WithInput(stdin).WithOutput(stdout)
	if err := form.Run(); err != nil {
		return nil, err
	}
	return selected, nil
}

func promptOverwriteHuh(targetPath string, managed bool, stdin io.Reader, stdout io.Writer) (bool, error) {
	var confirmed bool
	title := fmt.Sprintf("%s already exists. Overwrite?", targetPath)
	if !managed {
		title = fmt.Sprintf("%s exists and was not generated by toolpod.\nOverwrite?", targetPath)
	}
	form := huh.NewForm(
		huh.NewGroup(
			huh.NewConfirm().
				Title(title).
				Affirmative("Overwrite").
				Negative("Skip").
				Value(&confirmed),
		),
	).WithInput(stdin).WithOutput(stdout)
	if err := form.Run(); err != nil {
		return false, err
	}
	return confirmed, nil
}

// checkFragmentFiles warns to stderr when a file fragment's source path does
// not exist on the host (spec §10b). Only leading "~" is expanded; absolute
// paths and paths without "~" are skipped (no host-side check needed).
func checkFragmentFiles(selectedFragments []string, stderr io.Writer) {
	home, err := os.UserHomeDir()
	if err != nil {
		return
	}
	for _, name := range selectedFragments {
		p, ok := Fragments()[name]
		if !ok {
			continue
		}
		for _, mount := range p.Mounts {
			if mount.Optional {
				continue
			}
			// Only expand a leading "~/" or exact "~" — don't touch
			// absolute paths or paths with "~" in the middle.
			var src string
			if strings.HasPrefix(mount.Source, "~/") {
				src = home + mount.Source[1:]
			} else if mount.Source == "~" {
				src = home
			} else {
				continue
			}
			if _, err := os.Stat(src); err != nil {
				fmt.Fprintf(stderr, "note: %s does not exist; this mount will be skipped at launch (it is marked optional).\n", mount.Source)
			}
		}
	}
}
