package scaffold

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/jgillich/toolpod/internal/profile"
)

func TestPresetsAreValid(t *testing.T) {
	for name, p := range Presets() {
		if err := validatePreset(name, p); err != nil {
			t.Errorf("preset %q: %v", name, err)
		}
	}
}

func TestValidatePresetRejectsIdentityFields(t *testing.T) {
	for name := range Presets() {
		t.Run(name, func(t *testing.T) {
			p := Presets()[name]
			// Mutate a copy to set a forbidden field and verify rejection.
			bad := p
			bad.Image = "evil:latest"
			if err := validatePreset(name, bad); err == nil {
				t.Errorf("expected error for preset %q with image set", name)
			}
			bad = p
			bad.Extends = "shell"
			if err := validatePreset(name, bad); err == nil {
				t.Errorf("expected error for preset %q with extends set", name)
			}
		})
	}
}

func TestGenerateYAMLWithCachesAndMounts(t *testing.T) {
	dir := t.TempDir()
	var stdout, stderr bytes.Buffer
	err := Run(context.Background(), Options{
		Profile:    "opencode",
		Presets:    []string{"npm", "go", "gitconfig", "ssh"},
		ProfileDir: dir,
	}, strings.NewReader(""), &stdout, &stderr)
	if err != nil {
		t.Fatalf("Run: %v\nstderr: %s", err, stderr.String())
	}
	// Note: this test uses mount presets (gitconfig, ssh) so checkPresetFiles
	// may emit warnings to stderr if those host files are absent. This test
	// only asserts on the generated file content, not stderr.

	data, err := os.ReadFile(filepath.Join(dir, "opencode.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	output := string(data)

	// Header marker
	if !strings.HasPrefix(output, "# Generated by toolpod init.\n") {
		t.Errorf("missing header marker, got:\n%s", output)
	}

	// extends
	if !strings.Contains(output, "extends: opencode") {
		t.Errorf("missing extends: opencode, got:\n%s", output)
	}

	// No command: [] (omitempty should handle this)
	if strings.Contains(output, "command:") {
		t.Errorf("should not emit command: in override, got:\n%s", output)
	}

	// Caches (alphabetical)
	if !strings.Contains(output, "go: ~/go") {
		t.Errorf("missing go cache, got:\n%s", output)
	}
	if !strings.Contains(output, "npm: ~/.npm") {
		t.Errorf("missing npm cache, got:\n%s", output)
	}

	// Mounts
	if !strings.Contains(output, "~/.gitconfig:") {
		t.Errorf("missing gitconfig mount, got:\n%s", output)
	}
	if !strings.Contains(output, "~/.ssh:") {
		t.Errorf("missing ssh mount, got:\n%s", output)
	}
	if !strings.Contains(output, "~/.ssh/known_hosts:") {
		t.Errorf("missing known_hosts mount, got:\n%s", output)
	}
	if !strings.Contains(output, "read_only: false") {
		t.Errorf("known_hosts should be read_only: false, got:\n%s", output)
	}
}

func TestIntegrationResolveGeneratedProfile(t *testing.T) {
	dir := t.TempDir()
	var stdout, stderr bytes.Buffer
	err := Run(context.Background(), Options{
		Profile:    "opencode",
		Presets:    []string{"npm", "go", "gitconfig", "ssh"},
		ProfileDir: dir,
	}, strings.NewReader(""), &stdout, &stderr)
	if err != nil {
		t.Fatalf("Run: %v\nstderr: %s", err, stderr.String())
	}

	cat, err := profile.LoadProfiles(dir)
	if err != nil {
		t.Fatalf("LoadProfiles: %v", err)
	}
	cfg, err := profile.ResolveProfile(cat, "opencode")
	if err != nil {
		t.Fatalf("ResolveProfile: %v", err)
	}
	if cfg.Caches["npm"] != "~/.npm" {
		t.Errorf("Caches[npm] = %q, want ~/.npm", cfg.Caches["npm"])
	}
	if cfg.Caches["go"] != "~/go" {
		t.Errorf("Caches[go] = %q, want ~/go", cfg.Caches["go"])
	}
	if cfg.Mounts["~/.gitconfig"].Source != "~/.gitconfig" {
		t.Errorf("gitconfig source = %q", cfg.Mounts["~/.gitconfig"].Source)
	}
	if !cfg.Mounts["~/.gitconfig"].ReadOnly {
		t.Error("gitconfig should be read-only")
	}
	if !cfg.Mounts["~/.ssh"].ReadOnly {
		t.Error("ssh should be read-only")
	}
	if cfg.Mounts["~/.ssh/known_hosts"].ReadOnly {
		t.Error("known_hosts should be read-write")
	}
	if cfg.Image != "ghcr.io/jdx/mise:latest" {
		t.Errorf("Image = %q, want inherited from built-in", cfg.Image)
	}
	if len(cfg.Command) != 1 || cfg.Command[0] != "opencode" {
		t.Errorf("Command = %v, want [opencode] inherited from built-in", cfg.Command)
	}
	// Presets install mise tools alongside their caches
	if cfg.Tools["node"] != "latest" {
		t.Errorf("Tools[node] = %q, want latest (from npm preset)", cfg.Tools["node"])
	}
	if cfg.Tools["go"] != "latest" {
		t.Errorf("Tools[go] = %q, want latest (from go preset)", cfg.Tools["go"])
	}
	if cfg.Tools["opencode"] != "latest" {
		t.Errorf("Tools[opencode] = %q, want latest (inherited from built-in)", cfg.Tools["opencode"])
	}
}

func TestSkipExistingWithoutForce(t *testing.T) {
	dir := t.TempDir()
	// Pre-create the file
	os.WriteFile(filepath.Join(dir, "opencode.yaml"), []byte("version: 1\n"), 0o644)

	var stdout, stderr bytes.Buffer
	err := Run(context.Background(), Options{
		Profile:    "opencode",
		Presets:    []string{"npm"},
		ProfileDir: dir,
	}, strings.NewReader(""), &stdout, &stderr)
	if err == nil {
		t.Fatal("expected error for existing file without --force")
	}
	if !strings.Contains(err.Error(), "already exists") {
		t.Errorf("error should mention 'already exists', got: %v", err)
	}
}

func TestForceOverwritesExisting(t *testing.T) {
	dir := t.TempDir()
	os.WriteFile(filepath.Join(dir, "opencode.yaml"), []byte("# Generated by toolpod init.\nversion: 1\nextends: opencode\n"), 0o644)

	var stdout, stderr bytes.Buffer
	err := Run(context.Background(), Options{
		Profile:    "opencode",
		Presets:    []string{"npm"},
		Force:      true,
		ProfileDir: dir,
	}, strings.NewReader(""), &stdout, &stderr)
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	data, _ := os.ReadFile(filepath.Join(dir, "opencode.yaml"))
	if !strings.Contains(string(data), "npm: ~/.npm") {
		t.Errorf("file should contain npm cache after force overwrite")
	}
}

func TestDryRunDoesNotWrite(t *testing.T) {
	dir := t.TempDir()
	var stdout, stderr bytes.Buffer
	err := Run(context.Background(), Options{
		Profile:    "opencode",
		Presets:    []string{"npm"},
		DryRun:     true,
		ProfileDir: dir,
	}, strings.NewReader(""), &stdout, &stderr)
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, "opencode.yaml")); !os.IsNotExist(err) {
		t.Error("dry-run should not write a file")
	}
	output := stdout.String()
	if !strings.Contains(output, "dry-run") {
		t.Errorf("dry-run output should mention 'dry-run', got: %s", output)
	}
	if strings.Contains(output, "created") {
		t.Error("dry-run should not say 'created'")
	}
}

func TestDryRunWithForceDoesNotPrompt(t *testing.T) {
	dir := t.TempDir()
	os.WriteFile(filepath.Join(dir, "opencode.yaml"), []byte("version: 1\n"), 0o644)

	var stdout, stderr bytes.Buffer
	err := Run(context.Background(), Options{
		Profile:    "opencode",
		Presets:    []string{"npm"},
		DryRun:     true,
		Force:      true,
		ProfileDir: dir,
	}, strings.NewReader(""), &stdout, &stderr)
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, "opencode.yaml")); err != nil {
		t.Error("dry-run+force should not modify existing file")
	}
}

func TestForceInteractiveDeclinePrompt(t *testing.T) {
	dir := t.TempDir()
	// File without the toolpod header marker → triggers overwrite prompt
	os.WriteFile(filepath.Join(dir, "opencode.yaml"), []byte("version: 1\n"), 0o644)
	var stdout, stderr bytes.Buffer
	err := Run(context.Background(), Options{
		Profile:     "opencode",
		Presets:     []string{"npm"},
		Force:       true,
		Interactive: true,
		ProfileDir:  dir,
	}, strings.NewReader("n\n"), &stdout, &stderr)
	if err != nil {
		t.Fatalf("declining prompt should not error, got: %v", err)
	}
	if !strings.Contains(stdout.String(), "skipped") {
		t.Error("should print skipped")
	}
	// File should be unchanged
	data, _ := os.ReadFile(filepath.Join(dir, "opencode.yaml"))
	if string(data) != "version: 1\n" {
		t.Error("file should be unchanged after declining overwrite")
	}
}

func TestInteractiveOverwritePromptDecline(t *testing.T) {
	dir := t.TempDir()
	os.WriteFile(filepath.Join(dir, "opencode.yaml"), []byte(headerMarker+"\nversion: 1\nextends: opencode\n"), 0o644)
	var stdout, stderr bytes.Buffer
	// No Profile/Presets provided → wizard triggers → overwrite prompt shows
	err := Run(context.Background(), Options{
		Interactive: true,
		ProfileDir:  dir,
	}, strings.NewReader("opencode\nnpm\nn\n"), &stdout, &stderr)
	if err != nil {
		t.Fatalf("declining prompt should not error, got: %v", err)
	}
	if !strings.Contains(stdout.String(), "skipped") {
		t.Error("should print skipped")
	}
	data, _ := os.ReadFile(filepath.Join(dir, "opencode.yaml"))
	if string(data) != headerMarker+"\nversion: 1\nextends: opencode\n" {
		t.Error("file should be unchanged after declining overwrite")
	}
}

func TestInteractiveOverwritePromptAccept(t *testing.T) {
	dir := t.TempDir()
	os.WriteFile(filepath.Join(dir, "opencode.yaml"), []byte(headerMarker+"\nversion: 1\nextends: opencode\n"), 0o644)
	var stdout, stderr bytes.Buffer
	// No Profile/Presets provided → wizard triggers → overwrite prompt shows
	err := Run(context.Background(), Options{
		Interactive: true,
		ProfileDir:  dir,
	}, strings.NewReader("opencode\nnpm\ny\n"), &stdout, &stderr)
	if err != nil {
		t.Fatalf("accepting prompt should not error, got: %v", err)
	}
	if !strings.Contains(stdout.String(), "created") {
		t.Errorf("should print created, got: %s", stdout.String())
	}
	data, _ := os.ReadFile(filepath.Join(dir, "opencode.yaml"))
	if !strings.Contains(string(data), "npm: ~/.npm") {
		t.Error("file should contain npm cache from new generation")
	}
}

func TestExplicitArgsNoOverwritePrompt(t *testing.T) {
	dir := t.TempDir()
	os.WriteFile(filepath.Join(dir, "opencode.yaml"), []byte(headerMarker+"\nversion: 1\nextends: opencode\n"), 0o644)
	var stdout, stderr bytes.Buffer
	// All args provided explicitly in a TTY-like test → no wizard → no prompt
	err := Run(context.Background(), Options{
		Profile:     "opencode",
		Presets:     []string{"npm"},
		Interactive: true,
		ProfileDir:  dir,
	}, strings.NewReader(""), &stdout, &stderr)
	if err == nil {
		t.Fatal("expected error for existing file with explicit args and no --force")
	}
	if !strings.Contains(err.Error(), "already exists") {
		t.Errorf("error should mention 'already exists', got: %v", err)
	}
}

func TestDryRunInteractivePrompts(t *testing.T) {
	dir := t.TempDir()
	input := strings.NewReader("opencode\nnpm\n")
	var stdout, stderr bytes.Buffer
	err := Run(context.Background(), Options{
		DryRun:      true,
		Interactive: true,
		ProfileDir:  dir,
	}, input, &stdout, &stderr)
	if err != nil {
		t.Fatalf("Run: %v\nstderr: %s", err, stderr.String())
	}
	// Prompts go to stderr
	if !strings.Contains(stderr.String(), "Profile:") {
		t.Error("should prompt for profile on stderr")
	}
	if !strings.Contains(stderr.String(), "Presets") {
		t.Error("should prompt for presets on stderr")
	}
	// YAML goes to stdout
	if !strings.Contains(stdout.String(), "extends: opencode") {
		t.Error("stdout should contain generated YAML")
	}
	// No file written
	if _, err := os.Stat(filepath.Join(dir, "opencode.yaml")); !os.IsNotExist(err) {
		t.Error("dry-run should not write a file")
	}
}

func TestUnknownPresetRejected(t *testing.T) {
	dir := t.TempDir()
	var stdout, stderr bytes.Buffer
	err := Run(context.Background(), Options{
		Profile:    "opencode",
		Presets:    []string{"npm", "yarn"},
		ProfileDir: dir,
	}, strings.NewReader(""), &stdout, &stderr)
	if err == nil {
		t.Fatal("expected error for unknown preset")
	}
	if !strings.Contains(err.Error(), "unknown preset: yarn") {
		t.Errorf("error should mention 'unknown preset: yarn', got: %v", err)
	}
	// File should not be written
	if _, err := os.Stat(filepath.Join(dir, "opencode.yaml")); !os.IsNotExist(err) {
		t.Error("file should not be written when preset is unknown")
	}
}

func TestUnknownProfileRejected(t *testing.T) {
	dir := t.TempDir()
	var stdout, stderr bytes.Buffer
	err := Run(context.Background(), Options{
		Profile:    "rustdev",
		Presets:    []string{"npm"},
		ProfileDir: dir,
	}, strings.NewReader(""), &stdout, &stderr)
	if err == nil {
		t.Fatal("expected error for unknown profile")
	}
	if !strings.Contains(err.Error(), "unknown built-in profile: rustdev") {
		t.Errorf("error should mention 'unknown built-in profile', got: %v", err)
	}
}

func TestNonInteractiveMissingProfile(t *testing.T) {
	dir := t.TempDir()
	var stdout, stderr bytes.Buffer
	err := Run(context.Background(), Options{
		ProfileDir: dir,
	}, strings.NewReader(""), &stdout, &stderr)
	if err == nil {
		t.Fatal("expected error for missing profile in non-interactive mode")
	}
	if !strings.Contains(err.Error(), "profile name is required") {
		t.Errorf("error should mention 'profile name is required', got: %v", err)
	}
}

func TestNoPresetsProducesJustExtends(t *testing.T) {
	dir := t.TempDir()
	var stdout, stderr bytes.Buffer
	err := Run(context.Background(), Options{
		Profile:    "shell",
		ProfileDir: dir,
	}, strings.NewReader(""), &stdout, &stderr)
	if err != nil {
		t.Fatalf("Run: %v\nstderr: %s", err, stderr.String())
	}
	data, err := os.ReadFile(filepath.Join(dir, "shell.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	output := string(data)
	if !strings.Contains(output, "extends: shell") {
		t.Errorf("should contain extends: shell, got:\n%s", output)
	}
	if strings.Contains(output, "caches:") {
		t.Errorf("should not contain caches with no presets, got:\n%s", output)
	}
	if strings.Contains(output, "mounts:") {
		t.Errorf("should not contain mounts with no presets, got:\n%s", output)
	}
}

func TestPresetMergeProducesCorrectResult(t *testing.T) {
	dir := t.TempDir()
	var stdout, stderr bytes.Buffer
	err := Run(context.Background(), Options{
		Profile:    "opencode",
		Presets:    []string{"npm", "ssh"},
		ProfileDir: dir,
	}, strings.NewReader(""), &stdout, &stderr)
	if err != nil {
		t.Fatalf("Run: %v\nstderr: %s", err, stderr.String())
	}

	cat, _ := profile.LoadProfiles(dir)
	cfg, _ := profile.ResolveProfile(cat, "opencode")
	if cfg.Caches["npm"] != "~/.npm" {
		t.Errorf("Caches[npm] = %q", cfg.Caches["npm"])
	}
	if _, ok := cfg.Mounts["~/.ssh"]; !ok {
		t.Error("missing ~/.ssh mount")
	}
	if _, ok := cfg.Mounts["~/.ssh/known_hosts"]; !ok {
		t.Error("missing ~/.ssh/known_hosts mount")
	}
}

func TestPromptsGoToStderr(t *testing.T) {
	dir := t.TempDir()
	// Non-interactive mode (Interactive not set, defaults to false) should
	// not write prompts. Uses "npm" preset which has no file mounts, so
	// checkPresetFiles produces no stderr output either.
	var stdout, stderr bytes.Buffer
	err := Run(context.Background(), Options{
		Profile:    "opencode",
		Presets:    []string{"npm"},
		ProfileDir: dir,
	}, strings.NewReader(""), &stdout, &stderr)
	if err != nil {
		t.Fatalf("Run: %v\nstderr: %s", err, stderr.String())
	}
	if stderr.String() != "" {
		t.Errorf("non-interactive mode should not write to stderr, got: %q", stderr.String())
	}
}

func TestInteractiveWizard(t *testing.T) {
	dir := t.TempDir()
	// Simulated stdin: first line = profile name, second line = preset names.
	input := strings.NewReader("opencode\nnpm,gitconfig\n")
	var stdout, stderr bytes.Buffer
	err := Run(context.Background(), Options{
		Interactive: true,
		ProfileDir:  dir,
	}, input, &stdout, &stderr)
	if err != nil {
		t.Fatalf("Run: %v\nstderr: %s", err, stderr.String())
	}
	data, err := os.ReadFile(filepath.Join(dir, "opencode.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	output := string(data)
	if !strings.Contains(output, "extends: opencode") {
		t.Errorf("missing extends: opencode, got:\n%s", output)
	}
	if !strings.Contains(output, "npm: ~/.npm") {
		t.Errorf("missing npm cache, got:\n%s", output)
	}
	if !strings.Contains(output, "~/.gitconfig:") {
		t.Errorf("missing gitconfig mount, got:\n%s", output)
	}
	// Prompts should go to stderr, not stdout
	if strings.Contains(stdout.String(), "Available built-in profiles") {
		t.Error("profile prompt should not go to stdout")
	}
}

func TestDirectoryCreatedIfAbsent(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "nested", "profiles")
	var stdout, stderr bytes.Buffer
	err := Run(context.Background(), Options{
		Profile:    "opencode",
		Presets:    []string{"npm"},
		ProfileDir: dir,
	}, strings.NewReader(""), &stdout, &stderr)
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	info, err := os.Stat(dir)
	if err != nil {
		t.Fatalf("directory should exist: %v", err)
	}
	if !info.IsDir() {
		t.Error("should be a directory")
	}
}

func TestPostWriteValidationSurvivesBrokenSibling(t *testing.T) {
	dir := t.TempDir()
	// Pre-create a broken sibling YAML that would cause LoadProfiles(dir)
	// to error under the old post-write validation (which loaded the entire
	// user dir). The fix validates the generated content in isolation via
	// validateViaTempDir, so the broken sibling must NOT cause the valid
	// generated file to be deleted.
	if err := os.WriteFile(filepath.Join(dir, "broken.yaml"), []byte("key: \"[unterminated\n"), 0o644); err != nil {
		t.Fatalf("WriteFile broken.yaml: %v", err)
	}

	var stdout, stderr bytes.Buffer
	err := Run(context.Background(), Options{
		Profile:    "opencode",
		Presets:    []string{"npm"},
		ProfileDir: dir,
	}, strings.NewReader(""), &stdout, &stderr)
	if err != nil {
		t.Fatalf("Run: %v\nstderr: %s", err, stderr.String())
	}

	// The valid generated file must NOT be deleted despite the broken sibling.
	data, err := os.ReadFile(filepath.Join(dir, "opencode.yaml"))
	if err != nil {
		t.Fatalf("generated file was deleted despite being valid: %v", err)
	}
	if !strings.Contains(string(data), "extends: opencode") {
		t.Errorf("generated file should contain extends: opencode, got:\n%s", string(data))
	}
	if !strings.Contains(stdout.String(), "generated config is valid") {
		t.Errorf("stdout should confirm validation, got: %s", stdout.String())
	}
}

func TestPresetFileExistenceWarning(t *testing.T) {
	// Point HOME at an empty temp dir so mount preset sources don't exist.
	home := t.TempDir()
	t.Setenv("HOME", home)
	dir := t.TempDir()
	var stdout, stderr bytes.Buffer
	err := Run(context.Background(), Options{
		Profile:    "opencode",
		Presets:    []string{"gitconfig", "ssh", "netrc"},
		ProfileDir: dir,
	}, strings.NewReader(""), &stdout, &stderr)
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if !strings.Contains(stderr.String(), "warning:") {
		t.Errorf("stderr should contain file-existence warnings, got: %q", stderr.String())
	}
}
