version: 1
caches:
  semgrep: ~/.cache/semgrep
  trivy: ~/.cache/trivy
mounts:
  ~/.config/semgrep:
    source: ~/.config/semgrep
    create: true
    read_only: false
    optional: true
  ~/.config/trivy:
    source: ~/.config/trivy
    create: true
    read_only: false
    optional: true
  ~/.config/configstore/snyk.json:
    source: ~/.config/configstore/snyk.json
    read_only: false
    optional: true
tools:
  gitleaks: latest
  semgrep: latest
  snyk: latest
  trivy: latest
