package doctor

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestCheckSELinux(t *testing.T) {
	c := checkSELinux(true)
	if c.Status != Pass || c.Name != "selinux" {
		t.Fatalf("enforcing: check = %+v, want pass 'selinux'", c)
	}
	if !strings.Contains(c.Message, "label=disable") {
		t.Errorf("enforcing: message should mention label=disable; got %q", c.Message)
	}

	c = checkSELinux(false)
	if c.Status != Pass {
		t.Fatalf("not enforcing: check = %+v, want pass", c)
	}
	if strings.Contains(c.Message, "label=disable") {
		t.Errorf("not enforcing: message should not mention label=disable; got %q", c.Message)
	}
}

func TestCheckWorkspaceWritable(t *testing.T) {
	dir := t.TempDir()
	c := checkWorkspaceWritable(context.Background(), dir)
	if c.Status != Pass {
		t.Errorf("writable dir: status = %s, want pass", c.Status)
	}
}

func TestCheckWorkspaceNotWritable(t *testing.T) {
	if os.Geteuid() == 0 {
		t.Skip("running as root: file permissions are not enforced")
	}
	dir := t.TempDir()
	err := os.Chmod(dir, 0o444)
	if err != nil {
		t.Skip("cannot chmod on this OS")
	}
	defer os.Chmod(dir, 0o755)
	c := checkWorkspaceWritable(context.Background(), dir)
	if c.Status == Pass {
		t.Error("read-only dir should not pass")
	}
}

func TestCheckProjectTools(t *testing.T) {
	dir := t.TempDir()
	os.WriteFile(filepath.Join(dir, ".tool-versions"), []byte("node 22\npython 3.13\n"), 0o644)
	c := checkProjectTools(context.Background(), dir)
	if c.Status != Pass {
		t.Errorf("status = %s, want pass", c.Status)
	}
	if !strings.Contains(c.Message, "node@22") {
		t.Errorf("message should list node@22; got %q", c.Message)
	}
}

func TestCheckProjectToolsNone(t *testing.T) {
	dir := t.TempDir()
	c := checkProjectTools(context.Background(), dir)
	if c.Status != Info {
		t.Errorf("no tool files: status = %s, want info", c.Status)
	}
}

func TestCheckProfileValidityIgnoresFragments(t *testing.T) {
	// Built-in fragments resolve without version/command/image; they must not
	// be validated as launchable profiles. typescript extends javascript, which
	// used to trip the base-profile tolerance and fail the check.
	c := checkProfileValidity("")
	if c.Status != Pass {
		t.Fatalf("status = %s, want pass, message: %s", c.Status, c.Message)
	}
}

func TestCheckUserOverridesNoGitconfig(t *testing.T) {
	dir := t.TempDir()
	// Create a user override for opencode that mounts no gitconfig.
	os.WriteFile(filepath.Join(dir, "opencode.yaml"), []byte(
		"# Generated by tpod init.\nversion: 1\nextends: opencode\n"), 0o644)

	checks := checkUserOverrides(dir)
	if len(checks) != 1 {
		t.Fatalf("expected 1 check, got %d", len(checks))
	}
	if checks[0].Name != "gitconfig" || checks[0].Status != Info {
		t.Errorf("expected gitconfig Info check, got %+v", checks[0])
	}
	if !strings.Contains(checks[0].Message, "not mounted") {
		t.Errorf("expected 'not mounted' hint, got: %s", checks[0].Message)
	}
}

func TestCheckUserOverridesWithCachesAndGitconfig(t *testing.T) {
	dir := t.TempDir()
	os.WriteFile(filepath.Join(dir, "opencode.yaml"), []byte(
		"version: 1\nextends: opencode\ncaches:\n  npm: ~/.npm\nmounts:\n  ~/.gitconfig:\n    source: ~/.gitconfig\n    read_only: true\n"), 0o644)

	checks := checkUserOverrides(dir)
	if len(checks) != 1 {
		t.Fatalf("expected 1 Pass check, got %d", len(checks))
	}
	if checks[0].Status != Pass {
		t.Errorf("Status = %v, want Pass (caches and gitconfig present)", checks[0].Status)
	}
}

func TestCheckUserOverridesNoUserFiles(t *testing.T) {
	dir := t.TempDir()

	checks := checkUserOverrides(dir)
	if len(checks) != 1 {
		t.Fatalf("expected 1 check, got %d", len(checks))
	}
	if checks[0].Status != Info {
		t.Errorf("Status = %v, want Info (migration notice for no user overrides)", checks[0].Status)
	}
}
