package doctor

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestCheckWorkspaceWritable(t *testing.T) {
	dir := t.TempDir()
	c := checkWorkspaceWritable(context.Background(), dir)
	if c.Status != Pass {
		t.Errorf("writable dir: status = %s, want pass", c.Status)
	}
}

func TestCheckWorkspaceNotWritable(t *testing.T) {
	dir := t.TempDir()
	err := os.Chmod(dir, 0o444)
	if err != nil {
		t.Skip("cannot chmod on this OS")
	}
	defer os.Chmod(dir, 0o755)
	c := checkWorkspaceWritable(context.Background(), dir)
	if c.Status == Pass {
		t.Error("read-only dir should not pass")
	}
}

func TestCheckProjectTools(t *testing.T) {
	dir := t.TempDir()
	os.WriteFile(filepath.Join(dir, ".tool-versions"), []byte("node 22\npython 3.13\n"), 0o644)
	c := checkProjectTools(context.Background(), dir)
	if c.Status != Pass {
		t.Errorf("status = %s, want pass", c.Status)
	}
	if !strings.Contains(c.Message, "node@22") {
		t.Errorf("message should list node@22; got %q", c.Message)
	}
}

func TestCheckProjectToolsNone(t *testing.T) {
	dir := t.TempDir()
	c := checkProjectTools(context.Background(), dir)
	if c.Status != Info {
		t.Errorf("no tool files: status = %s, want info", c.Status)
	}
}

func TestCheckUserOverridesNoCachesNoGitconfig(t *testing.T) {
	dir := t.TempDir()
	// Create a user override for opencode with no caches and no gitconfig
	os.WriteFile(filepath.Join(dir, "opencode.yaml"), []byte(
		"# Generated by toolpod init.\nversion: 1\nextends: opencode\n"), 0o644)

	checks := checkUserOverrides(dir)
	if len(checks) < 2 {
		t.Fatalf("expected at least 2 checks (caches + gitconfig), got %d", len(checks))
	}
	var foundCaches, foundGitconfig bool
	for _, c := range checks {
		if c.Status != Info {
			t.Errorf("check %q: Status = %v, want Info", c.Name, c.Status)
		}
		if c.Name == "caches" && strings.Contains(c.Message, "none configured") {
			foundCaches = true
		}
		if c.Name == "gitconfig" && strings.Contains(c.Message, "not mounted") {
			foundGitconfig = true
		}
	}
	if !foundCaches {
		t.Error("missing caches check with 'none configured'")
	}
	if !foundGitconfig {
		t.Error("missing gitconfig check with 'not mounted'")
	}
}

func TestCheckUserOverridesWithCachesAndGitconfig(t *testing.T) {
	dir := t.TempDir()
	os.WriteFile(filepath.Join(dir, "opencode.yaml"), []byte(
		"version: 1\nextends: opencode\ncaches:\n  npm: ~/.npm\nmounts:\n  ~/.gitconfig:\n    source: ~/.gitconfig\n    read_only: true\n"), 0o644)

	checks := checkUserOverrides(dir)
	if len(checks) != 1 {
		t.Fatalf("expected 1 Pass check, got %d", len(checks))
	}
	if checks[0].Status != Pass {
		t.Errorf("Status = %v, want Pass (caches and gitconfig present)", checks[0].Status)
	}
}

func TestCheckUserOverridesNoUserFiles(t *testing.T) {
	dir := t.TempDir()

	checks := checkUserOverrides(dir)
	if len(checks) != 1 {
		t.Fatalf("expected 1 check, got %d", len(checks))
	}
	if checks[0].Status != Info {
		t.Errorf("Status = %v, want Info (migration notice for no user overrides)", checks[0].Status)
	}
}
